---
image: debian/testing
packages:
  - bundler
  - ruby-dev
  - lftp
secrets:
  - 7b748b62-e038-4ee9-b6ae-08c63f8222b5
  - fcc9631c-86a1-437d-95d4-9b5a140acaa0
tasks:
  - bundler: |
      cd blog
      bundle --local
  - build: |
      cd blog
      bundle exec jekyll build
      sed -i 's/Microsoft YaHei,微软雅黑,宋体,STXihei,华文细黑,//i' _site/assets/main.css
  - deploy: |
      echo 'www.webindie.nl,46.19.33.211 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMMqRI5cWKf+gHbyr7JBoiSHiloTbIawU2lhEM6F3/cKjbJSIbFgYZ8r63dQEe5Oyvhxx+k2+M53dt4OKB12C7U=' > .ssh/known_hosts
      cd blog
      lftp -f deploy.lftp
triggers:
  - action: email
    condition: failure
    to: frank@webindie.nl
