---
image: debian/testing
packages:
  - bundler
  - ruby-dev
  - lftp
secrets:
  - 1966aa97-432e-4657-910e-973298d9c40e
tasks:
  - bundler: |
      cd website
      bundle --local
  - build: |
      cd website
      bundle exec jekyll build
      sed -i 's/serif/sans-serif/i' _site/assets/main.css
  - deploy: |
      cd website
      lftp -f deploy.lftp
